fix: prevent `require` of .d.ts in local vite clone
This commit prevents the following error when using a local clone of vite:

    Error: Cannot find module 'types/fileTypes'